services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    expose:
    - 5432
    volumes:  
    - ./tables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:  
    - POSTGRES_PASSWORD=root

  redis:
    image: redis:7.0
    container_name: redis
    expose:
    - 6379
  
  discovery-server:
    image: benhassan98/discovery-server-image
    container_name: discovery-server
    expose:
    - 8761
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s  
  
  config-server:
    image: benhassan98/config-server-image
    container_name: config-server
    env_file:
    - .config-server_env
    expose:  
    - 8888
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s  
    depends_on:
      discovery-server:
        condition: service_healthy

  account-service:
    image: benhassan98/account-service-image
    container_name: account-service
    env_file:
    - .eureka_env
    expose:  
    - 8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy


  post-service:
    image: benhassan98/post-service-image
    container_name: post-service
    env_file:
    - .eureka_env
    expose:  
    - 8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy       



  chat-service:
    image: benhassan98/chat-service-image
    container_name: chat-service
    env_file:
    - .eureka_env
    expose:  
    - 8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy       



  notification-service:
    image: benhassan98/notification-service-image
    container_name: notification-service
    env_file:
    - .eureka_env
    expose:  
    - 8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy       
       
  auth-server:
    image: benhassan98/auth-server-image
    container_name: auth-server
    env_file:
    - .eureka_env
    expose:  
    - 8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy       
   
  gateway-service:
    image: benhassan98/gateway-service-image
    container_name: gateway-service
    env_file:
    - .eureka_env
    ports:  
    - 8080:8080
    depends_on:  
      config-server:
        condition: service_healthy
      discovery-server:      
        condition: service_healthy        



  bff-service:
    image: benhassan98/bff-service-image
    container_name: bff-service
    env_file:
    - .bff_env
    ports:  
    - 8081:8080
      
  frontent-service:
    image: benhassan98/frontend-service-image
    container_name: frontend-service
    ports:  
    - 9000:80
   
